=== coin-or/OS/trunk/OS/schemas/OSRepository.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Jun Ma (Northwestern University) -->
<xs:schema targetNamespace="os.optimizationservices.org" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="os.optimizationservices.org" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<!--OSRepository.xsd: current version - 1.0.0 -->
	<!--include: since version 1.0.0-->
	<xs:include schemaLocation="OSgL.xsd"/>
	<xs:element name="osRepository" type="OSRepository">
		<xs:annotation>
			<xs:documentation>since version 1.0.0</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="OSRepository">
		<xs:annotation>
			<xs:documentation>since version 1.0.0</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="description">
				<xs:annotation>
					<xs:documentation>since version 1.0.0</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="news" type="News">
				<xs:annotation>
					<xs:documentation>since version 1.0.0</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="instance" type="RepositoryInstance" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>since version 1.0.0</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="RepositoryInstance">
		<xs:annotation>
			<xs:documentation>since version 1.0.0</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="name" type="xs:string">
				<xs:annotation>
					<xs:documentation>since version 1.0.0</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="source" type="xs:string">
				<xs:annotation>
					<xs:documentation>since version 1.0.0</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="description" type="xs:string">
				<xs:annotation>
					<xs:documentation>since version 1.0.0</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="originalFileName" type="xs:string">
				<xs:annotation>
					<xs:documentation>since version 1.0.0</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="osDirectory" type="xs:string">
				<xs:annotation>
					<xs:documentation>since version 1.0.0</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="osFileName" type="xs:string">
				<xs:annotation>
					<xs:documentation>since version 1.0.0</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== coin-or/OS/trunk/OSRepository.xml
<?xml version="1.0" encoding="UTF-8"?><osRepository xmlns="os.optimizationservices.org" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="os.optimizationservices.org http://www.optimizationservices.org/schemas/osRepository.xsd">	<description>Optimization Services Repository (OSRepository)</description>	<news>		<el time="2006-02-01T09:30:00.000-06:00">First creation of the OSRepository. Original problems are mainly from the NetLib Repository (maintained by David Gay) and are all linear continuous. The "Kennington" problems from Netlib and John Chinneck's infeasible problem set are also included.  [Jun Ma (Northwestern Univeristy), Kipp Martin (University of Chicago) and Huanyuan Sheng (Northwestern Univeristy)]</el>	</news>	<!-- Netlib Problems-->	<instance>		<name>25FV47</name>		<source>Converted by Jun Ma, Kipp Martin, Huanyuan Sheng from the Netlib Repository. Originally supplied by John Reid on a tape sent to David Gay. </source>		<description>objectives: 1 (minimization); constraints: 821; variables: 1571; nonzeros (obj coefs + constraint coefs): 11127; reported optimal value: 5.5018458883E+03. This problem is sometimes called BP or BP1. </description>		<originalFileName>25fv47.mps</originalFileName>		<osDirectoty>linear/continuous/</osDirectoty>		<osFileName>25fv47.osil</osFileName>	</instance>	<instance>		<name>80BAU3B</name>		<source>Converted by Jun Ma, Kipp Martin, Huanyuan Sheng from the Netlib Repository. Originally supplied by Robert Fourer from Northwestern Univeristy. The source of the probelm is: W. Kurator and Harvey Greenberg, Energy Information Administration (Greenberg is now at the Univ. of Colorado - Denver). GREENBEA, GREENBEB: a large refinery model; see the book "A Model-Management Framework for Mathematical Programming" by Kenneth H. Palmer et al. (John Wiley and Sons, New York, 1984). </source>		<description>objectives: 1 (minimization); constraints: 2262; variables: 9799; nonzeros (obj coefs + constraint coefs): 29063; reported optimal value: 9.8723216072E+05</description>		<originalFileName>80bau3b.mps</originalFileName>		<osDirectoty>linear/continuous/</osDirectoty>		<osFileName>80bau3b.osil</osFileName>	</instance>	<instance>		<name>ADLITTLE</name>		<source>Converted by Jun Ma, Kipp Martin, Huanyuan Sheng from the Netlib Repository. Originally supplied by Michael Saunders from the Systems Optimization Laboratory at Stanford University.</source>		<description>objectives: 1 (minimization); constraints: 56; variables: 97; nonzeros (obj coefs + constraint coefs): 465; reported optimal value: 2.2549496316E+05			</description>		<originalFileName>adlittle.mps</originalFileName>		<osDirectoty>linear/continuous/</osDirectoty>		<osFileName>adlittle.osil</osFileName>	</instance>	<instance>		<name>AFIRO</name>		<source>Converted by Jun Ma, Kipp Martin, Huanyuan Sheng from the Netlib Repository. Originally supplied by Michael Saunders from the Systems Optimization Laboratory at Stanford University.</source>		<description>objectives: 1 (minimization); constraints: 27; variables: 32; nonzeros (obj coefs + constraint coefs): 88; reported optimal value: -4.6475314286E+02</description>		<originalFileName>afiro.mps</originalFileName>		<osDirectoty>linear/continuous/</osDirectoty>		<osFileName>afiro.osil</osFileName>	</instance>	<instance>		<name>AGG</name>		<source>Converted by Jun Ma, Kipp Martin, Huanyuan Sheng from the Netlib Repository. Originally supplied by Mauricio Resende and formulated by R. C. Leachman</source>		<description>objectives: 1 (minimization); constraints: 488; variables: 163; nonzeros (obj coefs + constraint coefs): 2541; reported optimal value: -3.5991767287E+07</description>		<originalFileName>agg.mps</originalFileName>		<osDirectoty>linear/continuous/</osDirectoty>		<osFileName>agg.osil</osFileName>	</instance>	<instance>		<name>AGG2</name>		<source>Converted by Jun Ma, Kipp Martin, Huanyuan Sheng from the Netlib Repository. Originally supplied by Mauricio Resende and formulated by R. C. Leachman</source>		<description>objectives: 1 (minimization); constraints: 516; variables: 302; nonzeros (obj coefs + constraint coefs): 4515; reported optimal value: -2.0239252356E+07</description>		<originalFileName>agg2.mps</originalFileName>		<osDirectoty>linear/continuous/</osDirectoty>		<osFileName>agg2.osil</osFileName>	</instance>	<instance>		<name>AGG3</name>		<source>Converted by Jun Ma, Kipp Martin, Huanyuan Sheng from the Netlib Repository. Originally supplied by Mauricio Resende and formulated by R. C. Leachman</source>		<description>objectives: 1 (minimization); constraints: 516; variables: 302; nonzeros (obj coefs + constraint coefs): 4531; reported optimal value: 1.0312115935E+07</description>		<originalFileName>agg3.mps</originalFileName>		<osDirectoty>linear/continuous/</osDirectoty>		<osFileName>agg3.osil</osFileName>	</instance>	<instance>		<name>BANDM</name>		<source>Converted by Jun Ma, Kipp Martin, Huanyuan Sheng from the Netlib Repository. Originally supplied by Michael Saunders from the Systems Optimization Laboratory at Stanford University.</source>		<description>objectives: 1 (minimization); constraints: 305; variables: 472; nonzeros (obj coefs + constraint coefs): 2659; reported optimal value: -1.5862801845E+02</description>		<originalFileName>bandm.mps</originalFileName>		<osDirectoty>linear/continuous/</osDirectoty>		<osFileName>bandm.osil</osFileName>	</instance>	<instance>		<name>BEACONFD</name>		<source>Converted by Jun Ma, Kipp Martin, Huanyuan Sheng from the Netlib Repository. Originally supplied by Michael Saunders from the Systems Optimization Laboratory at Stanford University.</source>		<description>objectives: 1 (minimization); constraints: 173; variables: 262; nonzeros (obj coefs + constraint coefs): 3476; reported optimal value: 3.3592485807E+04</description>		<originalFileName>beaconfd.mps</originalFileName>		<osDirectoty>linear/continuous/</osDirectoty>		<osFileName>beaconfd.osil</osFileName>	</instance>	<instance>		<name>BLEND</name>		<source>Converted by Jun Ma, Kipp Martin, Huanyuan Sheng from the Netlib Repository. Originally supplied by Nick Gould from the Harwell collection of LP test problems. </source>		<description>objectives: 1 (minimization); constraints: 74; variables: 83; nonzeros (obj coefs + constraint coefs): 521; reported optimal value: -3.0812149846E+01. Nick Gould says that BLEND "is is a variant of the [oil refinery] problem in Murtagh's book (the coefficients are different) which, in David Gay's understanding, John Reid obtained from the people at NPL. In converting the MPS file, Jun Ma filled the RHS section in the MPS file with dummy RHS labels. </description>		<originalFileName>blend.mps</originalFileName>		<osDirectoty>linear/continuous/</osDirectoty>		<osFileName>blend.osil</osFileName>	</instance>	<instance>		<name>BNL1</name>		<source>Converted by Jun Ma, Kipp Martin, Huanyuan Sheng from the Netlib Repository. Originally supplied by John Tomlin with the permission of Ketron.</source>		<description>objectives: 1 (minimization); constraints: 643; variables: 1175; nonzeros (obj coefs + constraint coefs): 6129; reported optimal value: 1.9776292856E+03. When solving the problem, MINOS 5.3 reports that 169 out of 1614 steps (10.47%) are degenerate.</description>		<originalFileName>bnl1.mps</originalFileName>		<osDirectoty>linear/continuous/</osDirectoty>		<osFileName>bnl1.osil</osFileName>	</instance>	<instance>		<name>BNL2</name>		<source>Converted by Jun Ma, Kipp Martin, Huanyuan Sheng from the Netlib Repository. Originally supplied by John Tomlin with the permission of Ketron.</source>		<description>objectives: 1 (minimization); constraints: 2324; variables: 3849; nonzeros (obj coefs + constraint coefs): 16124; reported optimal value: 1.8112365404E+03. When solving the problem, MINOS 5.3 reports that 906 out of 4914 steps (18.44%) are degenerate.</description>		<originalFileName>bnl2.mps</originalFileName>		<osDirectoty>linear/continuous/</osDirectoty>		<osFileName>bnl2.osil</osFileName>	</instance>	<instance>		<!-- possible warningunprepared constrain typeunprepared constrain typeunprepared constrain typeunprepared constrain type...-->		<name>BOEING1</name>		<source>Converted by Jun Ma, Kipp Martin, Huanyuan Sheng from the Netlib Repository. Originally supplied by Nick Gould from the Harwell collection of LP test problems.</source>		<description>objectives: 1 (minimization); constraints: 350; variables: 384; nonzeros (obj coefs + constraint coefs):3865; reported optimal value: -3.3521356751E+02. According to Nick Gould, BOEING1 and BOEING2 "have to do with flap settings on aircraft for economical operations".  These two problems were originally mixed-integer programming problems. These problems also had a few rows defined as linear combinations of other rows.  These rows are now given explicitly due to limits related with the MPS format.</description>		<originalFileName>boeing1.mps</originalFileName>		<osDirectoty>linear/continuous/</osDirectoty>		<osFileName>boeing1.osil</osFileName>	</instance>	<instance>		<!-- possible warningunprepared constrain typeunprepared constrain typeunprepared constrain typeunprepared constrain type...-->		<name>BOEING2</name>		<source>Converted by Jun Ma, Kipp Martin, Huanyuan Sheng from the Netlib Repository. Originally supplied by Nick Gould from the Harwell collection of LP test problems.</source>		<description>objectives: 1 (minimization); constraints: 166; variables: 143; nonzeros (obj coefs + constraint coefs): 1339; reported optimal value: -3.1501872802E+02. According to Nick Gould, BOEING1 and BOEING2 "have to do with flap settings on aircraft for economical operations". These two problems were originally mixed-integer programming problems. These problems also had a few rows defined as linear
